version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:final
    env_file: .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - mariadb_data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception_network
    restart: on-failure

  nginx:
    container_name: nginx
    image: nginx:final
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - wordpress
    env_file: .env
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress:final
    env_file: .env
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    networks:
      - inception_network
    restart: on-failure

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rukkyaa/data/mysql
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/rukkyaa/data/wordpress
      o: bind

networks:
  inception_network:
    driver: bridge