version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:final
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception_network
    restart: always

networks:
  inception_network:
    driver: bridge